### ISSUE TITLE
Failed Installation on High Sierra

### ISSUE THREAD

**Issue by harrychin** [souffle-lang/homebrew-souffle#2]
I attempted to install using the homebrew command `brew install souffle-lang/homebrew-souffle/souffle` but it returned this exception:

```
./configure
--disable-silent-rules
--prefix=/usr/local/Cellar/souffle/1.2.0


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/souffle-lang/homebrew-souffle/issues

/usr/local/Homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump': undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x000001028404d8> (NoMethodError)
Did you mean?  check_for_tap_ruby_files_locations
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `each'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

**Comment by mmcgr** [comment]
We were late seeing this issue, but the brew formula has now been updated, and will update automatically with each release. It's also been tested on High Sierra.


For the stable release
```
brew install souffle-lang/souffle/souffle
```

or for the latest developments
```
brew install --HEAD souffle-lang/souffle/souffle
```
